In [8]:
import pandas as pd

In [9]:
name_basic = pd.read_csv('data_imdb/name.basics.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(name_basic.info())
name_basic.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nconst             100 non-null    object
 1   primaryName        100 non-null    object
 2   birthYear          100 non-null    object
 3   deathYear          100 non-null    object
 4   primaryProfession  100 non-null    object
 5   knownForTitles     100 non-null    object
dtypes: object(6)
memory usage: 4.8+ KB
None

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0045537,tt0053137,tt0050419,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0037382,tt0071877,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0049189,tt0057345,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0078723,tt0077975,tt0072562,tt0080455"

In [10]:
title_akas = pd.read_csv('data_imdb/title.akas.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_akas.info())
title_akas.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   titleId          100 non-null    object
 1   ordering         100 non-null    int64
 2   title            100 non-null    object
 3   region           100 non-null    object
 4   language         100 non-null    object
 5   types            100 non-null    object
 6   attributes       100 non-null    object
 7   isOriginalTitle  100 non-null    int64
dtypes: int64(2), object(6)
memory usage: 6.4+ KB
None

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,\N,imdbDisplay,\N,0
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
3,tt0000001,4,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [11]:
title_basics = pd.read_csv('data_imdb/title.basics.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_basics.info())
title_basics.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          100 non-null    object
 1   titleType       100 non-null    object
 2   primaryTitle    100 non-null    object
 3   originalTitle   100 non-null    object
 4   isAdult         100 non-null    int64
 5   startYear       100 non-null    int64
 6   endYear         100 non-null    object
 7   runtimeMinutes  100 non-null    object
 8   genres          100 non-null    object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB
None

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"

In [12]:
title_crew = pd.read_csv('data_imdb/title.crew.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_crew.info())
title_crew.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tconst     100 non-null    object
 1   directors  100 non-null    object
 2   writers    100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB
None

      tconst  directors writers
0  tt0000001  nm0005690      \N
1  tt0000002  nm0721526      \N
2  tt0000003  nm0721526      \N
3  tt0000004  nm0721526      \N

In [14]:
title_episode = pd.read_csv('data_imdb/title.episode.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_episode.info())
title_episode.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tconst         100 non-null    object
 1   parentTconst   100 non-null    object
 2   seasonNumber   100 non-null    object
 3   episodeNumber  100 non-null    object
dtypes: object(4)
memory usage: 3.2+ KB
None

      tconst parentTconst seasonNumber episodeNumber
0  tt0041951    tt0041038            1             9
1  tt0042816    tt0989125            1            17
2  tt0042889    tt0989125           \N            \N
3  tt0043426    tt0040051            3            42

In [15]:
title_principals = pd.read_csv('data_imdb/title.principals.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_principals.info())
title_principals.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tconst      100 non-null    object
 1   ordering    100 non-null    int64
 2   nconst      100 non-null    object
 3   category    100 non-null    object
 4   job         100 non-null    object
 5   characters  100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB
None

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0374658,cinematographer,director of photography,\N
3,tt0000002,1,nm0721526,director,\N,\N

In [16]:
title_ratings = pd.read_csv('data_imdb/title.ratings.tsv.gz',compression='gzip', sep='\t', nrows=100)

print(title_ratings.info())
title_ratings.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tconst         100 non-null    object
 1   averageRating  100 non-null    float64
 2   numVotes       100 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.5+ KB
None

      tconst  averageRating  numVotes
0  tt0000001            5.7      1959
1  tt0000002            5.8       263
2  tt0000003            6.5      1793
3  tt0000004            5.6       179