In [1]:

import pandas as pd

In [2]:
genome_scores = pd.read_csv('data_mdl/genome-scores.zip',compression='zip', sep=',' , nrows=100)
print(genome_scores.info())
genome_scores.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   movieId    100 non-null    int64
 1   tagId      100 non-null    int64
 2   relevance  100 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 2.5 KB
None

   movieId  tagId  relevance
0        1      1    0.02500
1        1      2    0.02500
2        1      3    0.05775
3        1      4    0.09675

In [3]:
genome_tags = pd.read_csv('data_mdl/genome-tags.zip',compression='zip', sep=',' , nrows=100)
print(genome_tags.info())
genome_tags.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tagId   100 non-null    int64
 1   tag     100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB
None

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [4]:
links = pd.read_csv('data_mdl/links.zip',compression='zip', sep=',' , nrows=100)
print(links.info())
links.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  100 non-null    int64
 1   imdbId   100 non-null    int64
 2   tmdbId   100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB
None

   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [5]:
movies = pd.read_csv('data_mdl/movies.zip',compression='zip', sep=',' , nrows=100)

# Séparation titre et année
movies['year'] = movies['title'].str.extract('.*\((.*)\).*',expand = False)
movies['title'] = movies['title'].apply(lambda x: x[:-7])

# Séparation de la colonne genre
#movies['genres'] = movies['genres'].str.split('|').values
#movies = movies.explode(column=['genres'])
#movies = movies.join(pd.get_dummies(movies['genres'], prefix='genre_'))
#movies = movies.drop(['genres'], axis=1)
#movies = movies.groupby(['movieId', 'title', 'year']).sum().reset_index()

print(movies.info())
movies.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  100 non-null    int64
 1   title    100 non-null    object
 2   genres   100 non-null    object
 3   year     100 non-null    object
dtypes: int64(1), object(3)
memory usage: 3.2+ KB
None

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [6]:
tags = pd.read_csv('data_mdl/tags.zip',compression='zip', sep=',' , nrows=100)
print(tags.info())
tags.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     100 non-null    int64
 1   movieId    100 non-null    int64
 2   tag        100 non-null    object
 3   timestamp  100 non-null    int64
dtypes: int64(3), object(1)
memory usage: 3.2+ KB
None

   userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

In [7]:
ratings1 = pd.read_csv('data_mdl/ratings_part1.zip',compression='zip', sep=',' , nrows=100)
ratings2 = pd.read_csv('data_mdl/ratings_part2.zip',compression='zip', sep=',' , nrows=100)

ratings = pd.concat([ratings1, ratings2], axis=0)

print(ratings.info())
ratings.head(5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   userId      200 non-null    int64
 2   movieId     200 non-null    int64
 3   rating      200 non-null    float64
 4   timestamp   200 non-null    int64
dtypes: float64(1), int64(4)
memory usage: 9.4 KB
None

   Unnamed: 0  userId  movieId  rating   timestamp
0           0       1        2     3.5  1112486027
1           1       1       29     3.5  1112484676
2           2       1       32     3.5  1112484819
3           3       1       47     3.5  1112484727
4           4       1       50     3.5  1112484580